# Generated by Django 5.2.5 on 2025-08-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, related_name='lessons_taught', to='lmsapp.userprofile'),
        ),
    ]
